apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-devopsodia
  labels:
    app: devopsodia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsodia
  template:
    metadata:
      labels:
        app: devopsodia
    spec:
      # imagePullSecrets:
      #   - name: registry-secret
      containers:
      - name: container-devopsodia
<<<<<<< HEAD
        image: eagunuworld/primary-argocd:12
=======
        image: 34.174.116.217:8085/repository/primary-argocd:13
>>>>>>> 0ac213301b581d07cbf2a93406d0a65945b322b7
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devopsodia-svc
  labels:
    app: devopsodia
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
  - port: 80
  nodePort: 30004
  selector:
    app: devopsodia
